// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: category_normaliser.sql

package entities

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listCategoryNormalisers = `-- name: ListCategoryNormalisers :many
SELECT paknsave_category, woolworths_category, canonical_name
FROM category_normaliser
WHERE is_deleted = false
`

type ListCategoryNormalisersRow struct {
	PaknsaveCategory   pgtype.Text
	WoolworthsCategory pgtype.Text
	CanonicalName      string
}

// Every retailer word and what it canonicalises to, read once per write alongside the tree.
func (q *Queries) ListCategoryNormalisers(ctx context.Context) ([]ListCategoryNormalisersRow, error) {
	rows, err := q.db.Query(ctx, listCategoryNormalisers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCategoryNormalisersRow
	for rows.Next() {
		var i ListCategoryNormalisersRow
		if err := rows.Scan(&i.PaknsaveCategory, &i.WoolworthsCategory, &i.CanonicalName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
