// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: category.sql

package entities

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countCategories = `-- name: CountCategories :one
SELECT count(*) FROM category WHERE is_deleted = false
`

func (q *Queries) CountCategories(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countCategories)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertCategory = `-- name: InsertCategory :one
INSERT INTO category (parent_category_id, name)
VALUES ($1::uuid, $2::text)
RETURNING category_id, parent_category_id, name, display_name
`

type InsertCategoryParams struct {
	ParentCategoryID pgtype.UUID
	Name             string
}

type InsertCategoryRow struct {
	CategoryID       pgtype.UUID
	ParentCategoryID pgtype.UUID
	Name             string
	DisplayName      pgtype.Text
}

// Creates one node. The sync's only write to this table.
func (q *Queries) InsertCategory(ctx context.Context, arg InsertCategoryParams) (InsertCategoryRow, error) {
	row := q.db.QueryRow(ctx, insertCategory, arg.ParentCategoryID, arg.Name)
	var i InsertCategoryRow
	err := row.Scan(
		&i.CategoryID,
		&i.ParentCategoryID,
		&i.Name,
		&i.DisplayName,
	)
	return i, err
}

const listCategories = `-- name: ListCategories :many
SELECT category_id, parent_category_id, name, display_name
FROM category
WHERE is_deleted = false
ORDER BY category_id
`

type ListCategoriesRow struct {
	CategoryID       pgtype.UUID
	ParentCategoryID pgtype.UUID
	Name             string
	DisplayName      pgtype.Text
}

// The whole tree, read once at the start of a catalogue write.
func (q *Queries) ListCategories(ctx context.Context) ([]ListCategoriesRow, error) {
	rows, err := q.db.Query(ctx, listCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCategoriesRow
	for rows.Next() {
		var i ListCategoriesRow
		if err := rows.Scan(
			&i.CategoryID,
			&i.ParentCategoryID,
			&i.Name,
			&i.DisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
