// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package entities

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type BarcodeKind string

const (
	BarcodeKindGTIN     BarcodeKind = "GTIN"
	BarcodeKindPLU      BarcodeKind = "PLU"
	BarcodeKindINTERNAL BarcodeKind = "INTERNAL"
)

func (e *BarcodeKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = BarcodeKind(s)
	case string:
		*e = BarcodeKind(s)
	default:
		return fmt.Errorf("unsupported scan type for BarcodeKind: %T", src)
	}
	return nil
}

type NullBarcodeKind struct {
	BarcodeKind BarcodeKind
	Valid       bool // Valid is true if BarcodeKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullBarcodeKind) Scan(value interface{}) error {
	if value == nil {
		ns.BarcodeKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.BarcodeKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullBarcodeKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.BarcodeKind), nil
}

type StoreChain string

const (
	StoreChainWOOLWORTHS StoreChain = "WOOLWORTHS"
	StoreChainPAKNSAVE   StoreChain = "PAKNSAVE"
	StoreChainNEWWORLD   StoreChain = "NEWWORLD"
)

func (e *StoreChain) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = StoreChain(s)
	case string:
		*e = StoreChain(s)
	default:
		return fmt.Errorf("unsupported scan type for StoreChain: %T", src)
	}
	return nil
}

type NullStoreChain struct {
	StoreChain StoreChain
	Valid      bool // Valid is true if StoreChain is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullStoreChain) Scan(value interface{}) error {
	if value == nil {
		ns.StoreChain, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.StoreChain.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullStoreChain) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.StoreChain), nil
}

type SyncStatus string

const (
	SyncStatusRUNNING   SyncStatus = "RUNNING"
	SyncStatusSUCCEEDED SyncStatus = "SUCCEEDED"
	SyncStatusFAILED    SyncStatus = "FAILED"
)

func (e *SyncStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SyncStatus(s)
	case string:
		*e = SyncStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for SyncStatus: %T", src)
	}
	return nil
}

type NullSyncStatus struct {
	SyncStatus SyncStatus
	Valid      bool // Valid is true if SyncStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSyncStatus) Scan(value interface{}) error {
	if value == nil {
		ns.SyncStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SyncStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSyncStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SyncStatus), nil
}

type Category struct {
	CategoryID       pgtype.UUID
	ParentCategoryID pgtype.UUID
	Name             string
	DisplayName      pgtype.Text
	IsDeleted        bool
	DateCreatedUtc   pgtype.Timestamptz
	LastUpdatedUtc   pgtype.Timestamptz
}

type CategoryNormaliser struct {
	CategoryNormaliserID pgtype.UUID
	PaknsaveCategory     pgtype.Text
	WoolworthsCategory   pgtype.Text
	CanonicalName        string
	IsDeleted            bool
	DateCreatedUtc       pgtype.Timestamptz
	LastUpdatedUtc       pgtype.Timestamptz
}

type Product struct {
	ProductID      pgtype.UUID
	Barcode        pgtype.Text
	BarcodeType    NullBarcodeKind
	Name           string
	Brand          pgtype.Text
	PackSize       pgtype.Text
	IsDeleted      bool
	DateCreatedUtc pgtype.Timestamptz
	LastUpdatedUtc pgtype.Timestamptz
}

type ProductCategory struct {
	ProductCategoryID pgtype.UUID
	ProductID         pgtype.UUID
	CategoryID        pgtype.UUID
	IsDeleted         bool
	DateCreatedUtc    pgtype.Timestamptz
	LastUpdatedUtc    pgtype.Timestamptz
}

type ProductImage struct {
	ProductImageID   pgtype.UUID
	ProductID        pgtype.UUID
	StoreChain       StoreChain
	Position         int32
	SourceUrl        string
	SourceEtag       pgtype.Text
	FileName         pgtype.Text
	ContentSha256    pgtype.Text
	Bytes            pgtype.Int4
	Width            pgtype.Int4
	Height           pgtype.Int4
	DownloadedAtUtc  pgtype.Timestamptz
	PlaceholderAtUtc pgtype.Timestamptz
	IsDeleted        bool
	DateCreatedUtc   pgtype.Timestamptz
	LastUpdatedUtc   pgtype.Timestamptz
}

type RetailerSession struct {
	RetailerSessionID pgtype.UUID
	StoreChain        StoreChain
	Token             string
	ExpiresAtUtc      pgtype.Timestamptz
	IsDeleted         bool
	DateCreatedUtc    pgtype.Timestamptz
	LastUpdatedUtc    pgtype.Timestamptz
}

type Store struct {
	StoreID         pgtype.UUID
	Retailer        StoreChain
	RegionID        string
	ExternalStoreID pgtype.Text
	Name            string
	Latitude        pgtype.Float8
	Longitude       pgtype.Float8
	IsDeleted       bool
	DateCreatedUtc  pgtype.Timestamptz
	LastUpdatedUtc  pgtype.Timestamptz
}

type StoreProduct struct {
	StoreProductID    pgtype.UUID
	ProductID         pgtype.UUID
	StoreID           pgtype.UUID
	ExternalProductID string
	UnitOfMeasure     string
	IsInStock         pgtype.Bool
	IsDeleted         bool
	DateCreatedUtc    pgtype.Timestamptz
	LastUpdatedUtc    pgtype.Timestamptz
}

type StoreProductPrice struct {
	StoreProductPriceID int64
	StoreProductID      pgtype.UUID
	StoreID             pgtype.UUID
	PriceCents          int32
	SalePriceCents      pgtype.Int4
	IsSale              bool
	ObservedAtUtc       pgtype.Timestamptz
	IsDeleted           bool
	DateCreatedUtc      pgtype.Timestamptz
	LastUpdatedUtc      pgtype.Timestamptz
}

type SyncRun struct {
	SyncRunID       pgtype.UUID
	Status          SyncStatus
	StartedAtUtc    pgtype.Timestamptz
	FinishedAtUtc   pgtype.Timestamptz
	HeartbeatAtUtc  pgtype.Timestamptz
	ProductsCreated int32
	ProductsMatched int32
	StoreProducts   int32
	Delisted        int64
	ErrorMessage    pgtype.Text
	IsDeleted       bool
	DateCreatedUtc  pgtype.Timestamptz
	LastUpdatedUtc  pgtype.Timestamptz
}
