// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: product_image.sql

package entities

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const bulkMarkProductImagesDeleted = `-- name: BulkMarkProductImagesDeleted :exec
UPDATE product_image
SET is_deleted = true, last_updated_utc = now()
WHERE product_image_id = ANY($1::uuid[])
`

func (q *Queries) BulkMarkProductImagesDeleted(ctx context.Context, ids []pgtype.UUID) error {
	_, err := q.db.Exec(ctx, bulkMarkProductImagesDeleted, ids)
	return err
}

const bulkUpsertProductImages = `-- name: BulkUpsertProductImages :exec
INSERT INTO product_image (
    product_id, store_chain, position, source_url,
    file_name, content_sha256, source_etag, bytes, width, height, downloaded_at_utc, placeholder_at_utc
)
SELECT x.product_id,
       x.store_chain::store_chain,
       x.position,
       x.source_url,
       x.file_name,
       x.content_sha256,
       x.source_etag,
       x.bytes,
       x.width,
       x.height,
       x.downloaded_at_utc,
       x.placeholder_at_utc
FROM jsonb_to_recordset($1::jsonb) AS x(
    product_id uuid,
    store_chain text,
    position integer,
    source_url text,
    file_name text,
    content_sha256 text,
    source_etag text,
    bytes integer,
    width integer,
    height integer,
    downloaded_at_utc timestamptz,
    placeholder_at_utc timestamptz
)
ON CONFLICT (product_id, store_chain, position) WHERE is_deleted = false DO UPDATE
SET source_url         = EXCLUDED.source_url,
    file_name          = EXCLUDED.file_name,
    content_sha256     = EXCLUDED.content_sha256,
    source_etag        = EXCLUDED.source_etag,
    bytes              = EXCLUDED.bytes,
    width              = EXCLUDED.width,
    height             = EXCLUDED.height,
    downloaded_at_utc  = EXCLUDED.downloaded_at_utc,
    placeholder_at_utc = EXCLUDED.placeholder_at_utc,
    last_updated_utc   = now()
`

// One statement for a whole chunk of the harvest.
func (q *Queries) BulkUpsertProductImages(ctx context.Context, rows []byte) error {
	_, err := q.db.Exec(ctx, bulkUpsertProductImages, rows)
	return err
}

const countProductImages = `-- name: CountProductImages :one
SELECT count(*) FROM product_image WHERE is_deleted = false AND file_name IS NOT NULL
`

func (q *Queries) CountProductImages(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countProductImages)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const findProductImage = `-- name: FindProductImage :one
SELECT position, file_name, content_sha256, bytes, width, height, downloaded_at_utc
FROM product_image
WHERE product_id = $1
  AND position = $2::integer
  AND is_deleted = false
  AND file_name IS NOT NULL
`

type FindProductImageParams struct {
	ProductID pgtype.UUID
	Position  int32
}

type FindProductImageRow struct {
	Position        int32
	FileName        pgtype.Text
	ContentSha256   pgtype.Text
	Bytes           pgtype.Int4
	Width           pgtype.Int4
	Height          pgtype.Int4
	DownloadedAtUtc pgtype.Timestamptz
}

func (q *Queries) FindProductImage(ctx context.Context, arg FindProductImageParams) (FindProductImageRow, error) {
	row := q.db.QueryRow(ctx, findProductImage, arg.ProductID, arg.Position)
	var i FindProductImageRow
	err := row.Scan(
		&i.Position,
		&i.FileName,
		&i.ContentSha256,
		&i.Bytes,
		&i.Width,
		&i.Height,
		&i.DownloadedAtUtc,
	)
	return i, err
}

const listOrphanedProductImages = `-- name: ListOrphanedProductImages :many
SELECT pi.product_image_id, pi.product_id, pi.file_name
FROM product_image pi
LEFT JOIN product p ON p.product_id = pi.product_id AND p.is_deleted = false
WHERE pi.is_deleted = false
  AND pi.file_name IS NOT NULL
  AND p.product_id IS NULL
`

type ListOrphanedProductImagesRow struct {
	ProductImageID pgtype.UUID
	ProductID      pgtype.UUID
	FileName       pgtype.Text
}

// Stored files whose product has gone or been soft-deleted.
func (q *Queries) ListOrphanedProductImages(ctx context.Context) ([]ListOrphanedProductImagesRow, error) {
	rows, err := q.db.Query(ctx, listOrphanedProductImages)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOrphanedProductImagesRow
	for rows.Next() {
		var i ListOrphanedProductImagesRow
		if err := rows.Scan(&i.ProductImageID, &i.ProductID, &i.FileName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductImageWork = `-- name: ListProductImageWork :many
SELECT pi.product_image_id,
       pi.product_id,
       pi.store_chain,
       pi.source_url,
       pi.position,
       pi.file_name,
       pi.content_sha256,
       pi.source_etag,
       pi.downloaded_at_utc,
       pi.placeholder_at_utc
FROM product_image pi
JOIN product p USING (product_id)
WHERE pi.is_deleted = false
  AND p.is_deleted = false
  AND pi.product_id IN (
      SELECT due.product_id
      FROM product_image due
      JOIN product dp ON dp.product_id = due.product_id AND dp.is_deleted = false
      WHERE due.is_deleted = false
      GROUP BY due.product_id
      HAVING (
                 max(due.downloaded_at_utc) IS NOT NULL
                 AND max(due.downloaded_at_utc) < $1::timestamptz
             )
             OR (
                 max(due.downloaded_at_utc) IS NULL
                 AND (max(due.placeholder_at_utc) IS NULL
                      OR max(due.placeholder_at_utc)
                         < $2::timestamptz)
             )
      ORDER BY due.product_id
      LIMIT $3::integer
  )
ORDER BY pi.product_id, pi.store_chain, pi.position
`

type ListProductImageWorkParams struct {
	StaleBefore             pgtype.Timestamptz
	RetryPlaceholdersBefore pgtype.Timestamptz
	MaxProducts             int32
}

type ListProductImageWorkRow struct {
	ProductImageID   pgtype.UUID
	ProductID        pgtype.UUID
	StoreChain       StoreChain
	SourceUrl        string
	Position         int32
	FileName         pgtype.Text
	ContentSha256    pgtype.Text
	SourceEtag       pgtype.Text
	DownloadedAtUtc  pgtype.Timestamptz
	PlaceholderAtUtc pgtype.Timestamptz
}

// Every candidate for every product that needs any image work.
func (q *Queries) ListProductImageWork(ctx context.Context, arg ListProductImageWorkParams) ([]ListProductImageWorkRow, error) {
	rows, err := q.db.Query(ctx, listProductImageWork, arg.StaleBefore, arg.RetryPlaceholdersBefore, arg.MaxProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProductImageWorkRow
	for rows.Next() {
		var i ListProductImageWorkRow
		if err := rows.Scan(
			&i.ProductImageID,
			&i.ProductID,
			&i.StoreChain,
			&i.SourceUrl,
			&i.Position,
			&i.FileName,
			&i.ContentSha256,
			&i.SourceEtag,
			&i.DownloadedAtUtc,
			&i.PlaceholderAtUtc,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductImages = `-- name: ListProductImages :many
SELECT position, file_name, content_sha256, bytes, width, height, downloaded_at_utc
FROM product_image
WHERE product_id = $1 AND is_deleted = false AND file_name IS NOT NULL
ORDER BY position
`

type ListProductImagesRow struct {
	Position        int32
	FileName        pgtype.Text
	ContentSha256   pgtype.Text
	Bytes           pgtype.Int4
	Width           pgtype.Int4
	Height          pgtype.Int4
	DownloadedAtUtc pgtype.Timestamptz
}

// Serving. Only slots with a stored file, in display order.
func (q *Queries) ListProductImages(ctx context.Context, productID pgtype.UUID) ([]ListProductImagesRow, error) {
	rows, err := q.db.Query(ctx, listProductImages, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProductImagesRow
	for rows.Next() {
		var i ListProductImagesRow
		if err := rows.Scan(
			&i.Position,
			&i.FileName,
			&i.ContentSha256,
			&i.Bytes,
			&i.Width,
			&i.Height,
			&i.DownloadedAtUtc,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStoredImagesForProduct = `-- name: ListStoredImagesForProduct :many
SELECT product_image_id, store_chain, position, file_name, content_sha256
FROM product_image
WHERE product_id = $1 AND is_deleted = false AND file_name IS NOT NULL
ORDER BY store_chain, position
`

type ListStoredImagesForProductRow struct {
	ProductImageID pgtype.UUID
	StoreChain     StoreChain
	Position       int32
	FileName       pgtype.Text
	ContentSha256  pgtype.Text
}

// Every stored file for a product, whichever chain and position it came from.
func (q *Queries) ListStoredImagesForProduct(ctx context.Context, productID pgtype.UUID) ([]ListStoredImagesForProductRow, error) {
	rows, err := q.db.Query(ctx, listStoredImagesForProduct, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStoredImagesForProductRow
	for rows.Next() {
		var i ListStoredImagesForProductRow
		if err := rows.Scan(
			&i.ProductImageID,
			&i.StoreChain,
			&i.Position,
			&i.FileName,
			&i.ContentSha256,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markProductImageDeleted = `-- name: MarkProductImageDeleted :exec
UPDATE product_image
SET is_deleted = true, last_updated_utc = now()
WHERE product_image_id = $1
`

func (q *Queries) MarkProductImageDeleted(ctx context.Context, productImageID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markProductImageDeleted, productImageID)
	return err
}

const upsertHarvestedImage = `-- name: UpsertHarvestedImage :one
INSERT INTO product_image (
    product_id, store_chain, position, source_url,
    file_name, content_sha256, bytes, width, height, downloaded_at_utc, placeholder_at_utc
)
VALUES (
    $1, $2::store_chain, $3::integer,
    $4::text,
    $5::text, $6::text, $7::integer,
    $8::integer, $9::integer,
    $10::timestamptz, $11::timestamptz
)
ON CONFLICT (product_id, store_chain, position) WHERE is_deleted = false DO UPDATE
SET source_url         = EXCLUDED.source_url,
    file_name          = EXCLUDED.file_name,
    content_sha256     = EXCLUDED.content_sha256,
    source_etag        = EXCLUDED.source_etag,
    bytes              = EXCLUDED.bytes,
    width              = EXCLUDED.width,
    height             = EXCLUDED.height,
    downloaded_at_utc  = EXCLUDED.downloaded_at_utc,
    placeholder_at_utc = EXCLUDED.placeholder_at_utc,
    last_updated_utc   = now()
RETURNING product_image_id, product_id, store_chain, position, source_url, source_etag, file_name, content_sha256, bytes, width, height, downloaded_at_utc, placeholder_at_utc, is_deleted, date_created_utc, last_updated_utc
`

type UpsertHarvestedImageParams struct {
	ProductID        pgtype.UUID
	StoreChain       StoreChain
	Position         int32
	SourceUrl        string
	FileName         pgtype.Text
	ContentSha256    pgtype.Text
	Bytes            pgtype.Int4
	Width            pgtype.Int4
	Height           pgtype.Int4
	DownloadedAtUtc  pgtype.Timestamptz
	PlaceholderAtUtc pgtype.Timestamptz
}

// The harvest's write.
func (q *Queries) UpsertHarvestedImage(ctx context.Context, arg UpsertHarvestedImageParams) (ProductImage, error) {
	row := q.db.QueryRow(ctx, upsertHarvestedImage,
		arg.ProductID,
		arg.StoreChain,
		arg.Position,
		arg.SourceUrl,
		arg.FileName,
		arg.ContentSha256,
		arg.Bytes,
		arg.Width,
		arg.Height,
		arg.DownloadedAtUtc,
		arg.PlaceholderAtUtc,
	)
	var i ProductImage
	err := row.Scan(
		&i.ProductImageID,
		&i.ProductID,
		&i.StoreChain,
		&i.Position,
		&i.SourceUrl,
		&i.SourceEtag,
		&i.FileName,
		&i.ContentSha256,
		&i.Bytes,
		&i.Width,
		&i.Height,
		&i.DownloadedAtUtc,
		&i.PlaceholderAtUtc,
		&i.IsDeleted,
		&i.DateCreatedUtc,
		&i.LastUpdatedUtc,
	)
	return i, err
}

const upsertProductImageSource = `-- name: UpsertProductImageSource :one
INSERT INTO product_image (product_id, store_chain, position, source_url)
VALUES ($1, $2::store_chain, 1, $3::text)
ON CONFLICT (product_id, store_chain, position) WHERE is_deleted = false DO UPDATE
SET source_url       = EXCLUDED.source_url,
    last_updated_utc = now()
RETURNING product_image_id, product_id, store_chain, position, source_url, source_etag, file_name, content_sha256, bytes, width, height, downloaded_at_utc, placeholder_at_utc, is_deleted, date_created_utc, last_updated_utc
`

type UpsertProductImageSourceParams struct {
	ProductID  pgtype.UUID
	StoreChain StoreChain
	SourceUrl  string
}

// The catalogue sync's only write to this table.
func (q *Queries) UpsertProductImageSource(ctx context.Context, arg UpsertProductImageSourceParams) (ProductImage, error) {
	row := q.db.QueryRow(ctx, upsertProductImageSource, arg.ProductID, arg.StoreChain, arg.SourceUrl)
	var i ProductImage
	err := row.Scan(
		&i.ProductImageID,
		&i.ProductID,
		&i.StoreChain,
		&i.Position,
		&i.SourceUrl,
		&i.SourceEtag,
		&i.FileName,
		&i.ContentSha256,
		&i.Bytes,
		&i.Width,
		&i.Height,
		&i.DownloadedAtUtc,
		&i.PlaceholderAtUtc,
		&i.IsDeleted,
		&i.DateCreatedUtc,
		&i.LastUpdatedUtc,
	)
	return i, err
}
