// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: product_category.sql

package entities

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const bulkUpsertProductCategories = `-- name: BulkUpsertProductCategories :exec
INSERT INTO product_category (product_id, category_id)
SELECT x.product_id, x.category_id
FROM jsonb_to_recordset($1::jsonb) AS x(
    product_id  uuid,
    category_id uuid
)
ON CONFLICT (product_id) WHERE is_deleted = false DO UPDATE
SET category_id      = EXCLUDED.category_id,
    last_updated_utc = now()
`

// One statement per chunk of the catalogue write.
func (q *Queries) BulkUpsertProductCategories(ctx context.Context, rows []byte) error {
	_, err := q.db.Exec(ctx, bulkUpsertProductCategories, rows)
	return err
}

const countProductCategories = `-- name: CountProductCategories :one
SELECT count(*) FROM product_category WHERE is_deleted = false
`

func (q *Queries) CountProductCategories(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countProductCategories)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listProductCategoryPath = `-- name: ListProductCategoryPath :many
WITH RECURSIVE ancestry AS (
    SELECT c.category_id,
           c.parent_category_id,
           c.name::text AS name,
           c.display_name,
           0::integer   AS depth
    FROM product_category pc
    JOIN category c ON c.category_id = pc.category_id AND c.is_deleted = false
    WHERE pc.product_id = $1 AND pc.is_deleted = false

    UNION ALL

    SELECT parent.category_id,
           parent.parent_category_id,
           parent.name::text,
           parent.display_name,
           ancestry.depth + 1
    FROM ancestry
    JOIN category parent
      ON parent.category_id = ancestry.parent_category_id
     AND parent.is_deleted = false
    WHERE ancestry.depth < 16
)
SELECT category_id, parent_category_id, name, display_name, depth
FROM ancestry
ORDER BY depth DESC
`

type ListProductCategoryPathRow struct {
	CategoryID       pgtype.UUID
	ParentCategoryID pgtype.UUID
	Name             string
	DisplayName      pgtype.Text
	Depth            int32
}

// Where a product sits, and every ancestor above it, root first.
func (q *Queries) ListProductCategoryPath(ctx context.Context, productID pgtype.UUID) ([]ListProductCategoryPathRow, error) {
	rows, err := q.db.Query(ctx, listProductCategoryPath, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProductCategoryPathRow
	for rows.Next() {
		var i ListProductCategoryPathRow
		if err := rows.Scan(
			&i.CategoryID,
			&i.ParentCategoryID,
			&i.Name,
			&i.DisplayName,
			&i.Depth,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
