// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: product.sql

package entities

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countProducts = `-- name: CountProducts :one
SELECT count(*) FROM product WHERE is_deleted = false
`

func (q *Queries) CountProducts(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countProducts)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const findProductByBarcode = `-- name: FindProductByBarcode :one
SELECT product_id, barcode, barcode_type, name, brand, date_created_utc, last_updated_utc, is_deleted, pack_size FROM product
WHERE barcode_type = $1::barcode_kind
  AND barcode = $2::text
  AND is_deleted = false
`

type FindProductByBarcodeParams struct {
	BarcodeType BarcodeKind
	Barcode     string
}

// Identity lookup for GTIN and PLU. Namespaced, so a PLU can never match a GTIN.
func (q *Queries) FindProductByBarcode(ctx context.Context, arg FindProductByBarcodeParams) (Product, error) {
	row := q.db.QueryRow(ctx, findProductByBarcode, arg.BarcodeType, arg.Barcode)
	var i Product
	err := row.Scan(
		&i.ProductID,
		&i.Barcode,
		&i.BarcodeType,
		&i.Name,
		&i.Brand,
		&i.DateCreatedUtc,
		&i.LastUpdatedUtc,
		&i.IsDeleted,
		&i.PackSize,
	)
	return i, err
}

const findProductByIdentity = `-- name: FindProductByIdentity :one
SELECT product_id, barcode, barcode_type, name, brand, date_created_utc, last_updated_utc, is_deleted, pack_size FROM product
WHERE barcode IS NULL
  AND lower(coalesce(brand, '')) = lower(coalesce($1::text, ''))
  AND lower(name) = lower($2::text)
  AND lower(coalesce(pack_size, '')) = lower(coalesce($3::text, ''))
  AND is_deleted = false
`

type FindProductByIdentityParams struct {
	Brand    pgtype.Text
	Name     string
	PackSize pgtype.Text
}

// Identity lookup for products with no cross-retailer identifier. Mirrors
// idx_product_identity_when_unidentified.
func (q *Queries) FindProductByIdentity(ctx context.Context, arg FindProductByIdentityParams) (Product, error) {
	row := q.db.QueryRow(ctx, findProductByIdentity, arg.Brand, arg.Name, arg.PackSize)
	var i Product
	err := row.Scan(
		&i.ProductID,
		&i.Barcode,
		&i.BarcodeType,
		&i.Name,
		&i.Brand,
		&i.DateCreatedUtc,
		&i.LastUpdatedUtc,
		&i.IsDeleted,
		&i.PackSize,
	)
	return i, err
}

const insertProduct = `-- name: InsertProduct :one
INSERT INTO product (barcode, barcode_type, name, brand, pack_size)
VALUES (
    $2::text,
    $3::barcode_kind,
    $1,
    $4::text,
    $5::text
)
RETURNING product_id, barcode, barcode_type, name, brand, date_created_utc, last_updated_utc, is_deleted, pack_size
`

type InsertProductParams struct {
	Name        string
	Barcode     pgtype.Text
	BarcodeType NullBarcodeKind
	Brand       pgtype.Text
	PackSize    pgtype.Text
}

func (q *Queries) InsertProduct(ctx context.Context, arg InsertProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, insertProduct,
		arg.Name,
		arg.Barcode,
		arg.BarcodeType,
		arg.Brand,
		arg.PackSize,
	)
	var i Product
	err := row.Scan(
		&i.ProductID,
		&i.Barcode,
		&i.BarcodeType,
		&i.Name,
		&i.Brand,
		&i.DateCreatedUtc,
		&i.LastUpdatedUtc,
		&i.IsDeleted,
		&i.PackSize,
	)
	return i, err
}

const updateProductDetails = `-- name: UpdateProductDetails :one
UPDATE product
SET name             = $2,
    brand            = $3::text,
    pack_size        = $4::text,
    last_updated_utc = now()
WHERE product_id = $1
RETURNING product_id, barcode, barcode_type, name, brand, date_created_utc, last_updated_utc, is_deleted, pack_size
`

type UpdateProductDetailsParams struct {
	ProductID pgtype.UUID
	Name      string
	Brand     pgtype.Text
	PackSize  pgtype.Text
}

// Refreshes the mutable descriptive fields. Identity columns are never touched: changing
// a barcode would silently re-point every store_product row at a different product.
func (q *Queries) UpdateProductDetails(ctx context.Context, arg UpdateProductDetailsParams) (Product, error) {
	row := q.db.QueryRow(ctx, updateProductDetails,
		arg.ProductID,
		arg.Name,
		arg.Brand,
		arg.PackSize,
	)
	var i Product
	err := row.Scan(
		&i.ProductID,
		&i.Barcode,
		&i.BarcodeType,
		&i.Name,
		&i.Brand,
		&i.DateCreatedUtc,
		&i.LastUpdatedUtc,
		&i.IsDeleted,
		&i.PackSize,
	)
	return i, err
}
