// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: retailer_session.sql

package entities

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteRetailerSession = `-- name: DeleteRetailerSession :exec
UPDATE retailer_session
SET is_deleted = true, last_updated_utc = now()
WHERE store_chain = $1::store_chain AND is_deleted = false
`

func (q *Queries) DeleteRetailerSession(ctx context.Context, storeChain StoreChain) error {
	_, err := q.db.Exec(ctx, deleteRetailerSession, storeChain)
	return err
}

const findLiveRetailerSession = `-- name: FindLiveRetailerSession :one
SELECT store_chain, token, expires_at_utc
FROM retailer_session
WHERE store_chain = $1::store_chain
  AND is_deleted = false
  AND (expires_at_utc IS NULL OR expires_at_utc > $2::timestamptz)
`

type FindLiveRetailerSessionParams struct {
	StoreChain StoreChain
	Now        pgtype.Timestamptz
}

type FindLiveRetailerSessionRow struct {
	StoreChain   StoreChain
	Token        string
	ExpiresAtUtc pgtype.Timestamptz
}

// A NULL expiry means the retailer stated none, so it is usable until something rejects it.
func (q *Queries) FindLiveRetailerSession(ctx context.Context, arg FindLiveRetailerSessionParams) (FindLiveRetailerSessionRow, error) {
	row := q.db.QueryRow(ctx, findLiveRetailerSession, arg.StoreChain, arg.Now)
	var i FindLiveRetailerSessionRow
	err := row.Scan(&i.StoreChain, &i.Token, &i.ExpiresAtUtc)
	return i, err
}

const upsertRetailerSession = `-- name: UpsertRetailerSession :one
INSERT INTO retailer_session (store_chain, token, expires_at_utc)
VALUES ($1::store_chain, $2::text, $3::timestamptz)
ON CONFLICT (store_chain) WHERE is_deleted = false DO UPDATE
SET token            = EXCLUDED.token,
    expires_at_utc   = EXCLUDED.expires_at_utc,
    last_updated_utc = now()
RETURNING retailer_session_id, store_chain, token, expires_at_utc, is_deleted, date_created_utc, last_updated_utc
`

type UpsertRetailerSessionParams struct {
	StoreChain   StoreChain
	Token        string
	ExpiresAtUtc pgtype.Timestamptz
}

// Rotation replaces the live token rather than appending a new row.
func (q *Queries) UpsertRetailerSession(ctx context.Context, arg UpsertRetailerSessionParams) (RetailerSession, error) {
	row := q.db.QueryRow(ctx, upsertRetailerSession, arg.StoreChain, arg.Token, arg.ExpiresAtUtc)
	var i RetailerSession
	err := row.Scan(
		&i.RetailerSessionID,
		&i.StoreChain,
		&i.Token,
		&i.ExpiresAtUtc,
		&i.IsDeleted,
		&i.DateCreatedUtc,
		&i.LastUpdatedUtc,
	)
	return i, err
}
