// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: store.sql

package entities

import (
	"context"
)

const findStoreByChainAndRegion = `-- name: FindStoreByChainAndRegion :one
SELECT store_id, store_name, region_id, date_created_utc, last_updated_utc, is_deleted FROM store
WHERE store_name = $1::store_chain
  AND region_id = $2::text
  AND is_deleted = false
`

type FindStoreByChainAndRegionParams struct {
	StoreName StoreChain
	RegionID  string
}

func (q *Queries) FindStoreByChainAndRegion(ctx context.Context, arg FindStoreByChainAndRegionParams) (Store, error) {
	row := q.db.QueryRow(ctx, findStoreByChainAndRegion, arg.StoreName, arg.RegionID)
	var i Store
	err := row.Scan(
		&i.StoreID,
		&i.StoreName,
		&i.RegionID,
		&i.DateCreatedUtc,
		&i.LastUpdatedUtc,
		&i.IsDeleted,
	)
	return i, err
}

const listStoresByChain = `-- name: ListStoresByChain :many
SELECT store_id, store_name, region_id, date_created_utc, last_updated_utc, is_deleted FROM store
WHERE store_name = $1::store_chain AND is_deleted = false
ORDER BY region_id
`

func (q *Queries) ListStoresByChain(ctx context.Context, storeName StoreChain) ([]Store, error) {
	rows, err := q.db.Query(ctx, listStoresByChain, storeName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Store
	for rows.Next() {
		var i Store
		if err := rows.Scan(
			&i.StoreID,
			&i.StoreName,
			&i.RegionID,
			&i.DateCreatedUtc,
			&i.LastUpdatedUtc,
			&i.IsDeleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertStore = `-- name: UpsertStore :one
INSERT INTO store (store_name, region_id)
VALUES ($1::store_chain, $2::text)
ON CONFLICT (store_name, region_id) DO UPDATE
SET last_updated_utc = now(),
    is_deleted       = false
RETURNING store_id, store_name, region_id, date_created_utc, last_updated_utc, is_deleted
`

type UpsertStoreParams struct {
	StoreName StoreChain
	RegionID  string
}

func (q *Queries) UpsertStore(ctx context.Context, arg UpsertStoreParams) (Store, error) {
	row := q.db.QueryRow(ctx, upsertStore, arg.StoreName, arg.RegionID)
	var i Store
	err := row.Scan(
		&i.StoreID,
		&i.StoreName,
		&i.RegionID,
		&i.DateCreatedUtc,
		&i.LastUpdatedUtc,
		&i.IsDeleted,
	)
	return i, err
}
