// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: store_product.sql

package entities

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const bulkRecordStoreProductPrices = `-- name: BulkRecordStoreProductPrices :execrows
INSERT INTO store_product_price (store_product_id, store_id, price_cents, sale_price_cents, observed_at_utc)
SELECT x.store_product_id, x.store_id, x.price_cents, x.sale_price_cents,
       $1::timestamptz
FROM jsonb_to_recordset($2::jsonb) AS x(
    store_product_id uuid,
    store_id         uuid,
    price_cents      integer,
    sale_price_cents integer
)
WHERE NOT EXISTS (
    SELECT 1
    FROM store_product_price recent
    WHERE recent.store_product_id = x.store_product_id
      AND recent.store_id = x.store_id
      AND recent.is_deleted = false
      AND recent.observed_at_utc > $3::timestamptz
)
`

type BulkRecordStoreProductPricesParams struct {
	ObservedAt    pgtype.Timestamptz
	Rows          []byte
	ObservedAfter pgtype.Timestamptz
}

// Records today's price for a chunk of the catalogue, at most once per store product per day.
func (q *Queries) BulkRecordStoreProductPrices(ctx context.Context, arg BulkRecordStoreProductPricesParams) (int64, error) {
	result, err := q.db.Exec(ctx, bulkRecordStoreProductPrices, arg.ObservedAt, arg.Rows, arg.ObservedAfter)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countStoreProducts = `-- name: CountStoreProducts :one
SELECT count(*) FROM store_product
WHERE store_id = $1 AND is_deleted = false
`

func (q *Queries) CountStoreProducts(ctx context.Context, storeID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countStoreProducts, storeID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const findStoreProductByExternalID = `-- name: FindStoreProductByExternalID :one
SELECT store_product_id, product_id, store_id, external_product_id, unit_of_measure, is_in_stock, is_deleted, date_created_utc, last_updated_utc FROM store_product
WHERE store_id = $1 AND external_product_id = $2 AND is_deleted = false
`

type FindStoreProductByExternalIDParams struct {
	StoreID           pgtype.UUID
	ExternalProductID string
}

func (q *Queries) FindStoreProductByExternalID(ctx context.Context, arg FindStoreProductByExternalIDParams) (StoreProduct, error) {
	row := q.db.QueryRow(ctx, findStoreProductByExternalID, arg.StoreID, arg.ExternalProductID)
	var i StoreProduct
	err := row.Scan(
		&i.StoreProductID,
		&i.ProductID,
		&i.StoreID,
		&i.ExternalProductID,
		&i.UnitOfMeasure,
		&i.IsInStock,
		&i.IsDeleted,
		&i.DateCreatedUtc,
		&i.LastUpdatedUtc,
	)
	return i, err
}

const listKnownBarcodesByChain = `-- name: ListKnownBarcodesByChain :many
SELECT DISTINCT ON (sp.external_product_id)
       sp.external_product_id,
       p.barcode,
       p.barcode_type,
       pi.source_url AS img_url
FROM store_product sp
JOIN product p USING (product_id)
JOIN store s USING (store_id)
LEFT JOIN product_image pi
       ON pi.product_id = p.product_id
      AND pi.store_chain = s.retailer
      AND pi.position = 1
      AND pi.is_deleted = false
WHERE s.retailer = $1::store_chain
  AND p.barcode IS NOT NULL
  AND sp.is_deleted = false
  AND p.is_deleted = false
ORDER BY sp.external_product_id, sp.last_updated_utc DESC
`

type ListKnownBarcodesByChainRow struct {
	ExternalProductID string
	Barcode           pgtype.Text
	BarcodeType       NullBarcodeKind
	ImgUrl            pgtype.Text
}

// Feeds the barcode cache. Keyed by the retailer's own product id rather than by store,
// because a barcode is store-independent: what one store resolved is valid for all of that
// chain's stores.
func (q *Queries) ListKnownBarcodesByChain(ctx context.Context, retailer StoreChain) ([]ListKnownBarcodesByChainRow, error) {
	rows, err := q.db.Query(ctx, listKnownBarcodesByChain, retailer)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListKnownBarcodesByChainRow
	for rows.Next() {
		var i ListKnownBarcodesByChainRow
		if err := rows.Scan(
			&i.ExternalProductID,
			&i.Barcode,
			&i.BarcodeType,
			&i.ImgUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentStoreProductPrices = `-- name: ListRecentStoreProductPrices :many
SELECT store_product_price_id, store_product_id, store_id, price_cents, sale_price_cents,
       is_sale, observed_at_utc
FROM store_product_price
WHERE store_product_id = $1 AND store_id = $2 AND is_deleted = false
ORDER BY observed_at_utc DESC
`

type ListRecentStoreProductPricesParams struct {
	StoreProductID pgtype.UUID
	StoreID        pgtype.UUID
}

type ListRecentStoreProductPricesRow struct {
	StoreProductPriceID int64
	StoreProductID      pgtype.UUID
	StoreID             pgtype.UUID
	PriceCents          int32
	SalePriceCents      pgtype.Int4
	IsSale              bool
	ObservedAtUtc       pgtype.Timestamptz
}

// The price history for one store product at one store, newest first.
func (q *Queries) ListRecentStoreProductPrices(ctx context.Context, arg ListRecentStoreProductPricesParams) ([]ListRecentStoreProductPricesRow, error) {
	rows, err := q.db.Query(ctx, listRecentStoreProductPrices, arg.StoreProductID, arg.StoreID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRecentStoreProductPricesRow
	for rows.Next() {
		var i ListRecentStoreProductPricesRow
		if err := rows.Scan(
			&i.StoreProductPriceID,
			&i.StoreProductID,
			&i.StoreID,
			&i.PriceCents,
			&i.SalePriceCents,
			&i.IsSale,
			&i.ObservedAtUtc,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markStoreProductsUnseenAsDeleted = `-- name: MarkStoreProductsUnseenAsDeleted :execrows
UPDATE store_product
SET is_deleted = true, last_updated_utc = now()
WHERE store_id = $1
  AND is_deleted = false
  AND last_updated_utc < $2
`

type MarkStoreProductsUnseenAsDeletedParams struct {
	StoreID        pgtype.UUID
	LastUpdatedUtc pgtype.Timestamptz
}

// Soft-deletes anything the latest scrape did not touch, so a delisted product stops
// appearing without the scraper needing to diff the catalogue itself.
func (q *Queries) MarkStoreProductsUnseenAsDeleted(ctx context.Context, arg MarkStoreProductsUnseenAsDeletedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markStoreProductsUnseenAsDeleted, arg.StoreID, arg.LastUpdatedUtc)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertStoreProduct = `-- name: UpsertStoreProduct :one
INSERT INTO store_product (
    product_id, store_id, external_product_id, unit_of_measure, is_in_stock
)
VALUES ($1, $2, $3, $4, $5::boolean)
ON CONFLICT (store_id, external_product_id) DO UPDATE
SET product_id       = EXCLUDED.product_id,
    unit_of_measure  = EXCLUDED.unit_of_measure,
    is_in_stock      = EXCLUDED.is_in_stock,
    is_deleted       = false,
    last_updated_utc = now()
RETURNING store_product_id, product_id, store_id, external_product_id, unit_of_measure, is_in_stock, is_deleted, date_created_utc, last_updated_utc
`

type UpsertStoreProductParams struct {
	ProductID         pgtype.UUID
	StoreID           pgtype.UUID
	ExternalProductID string
	UnitOfMeasure     string
	IsInStock         pgtype.Bool
}

// Keyed on the retailer's own id, which is what the scraper knows. Deliberately no price:
// prices live in store_product_price and are fetched on demand.
func (q *Queries) UpsertStoreProduct(ctx context.Context, arg UpsertStoreProductParams) (StoreProduct, error) {
	row := q.db.QueryRow(ctx, upsertStoreProduct,
		arg.ProductID,
		arg.StoreID,
		arg.ExternalProductID,
		arg.UnitOfMeasure,
		arg.IsInStock,
	)
	var i StoreProduct
	err := row.Scan(
		&i.StoreProductID,
		&i.ProductID,
		&i.StoreID,
		&i.ExternalProductID,
		&i.UnitOfMeasure,
		&i.IsInStock,
		&i.IsDeleted,
		&i.DateCreatedUtc,
		&i.LastUpdatedUtc,
	)
	return i, err
}
