// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: store.sql

package entities

import (
	"context"
)

const findStoreByChainAndRegion = `-- name: FindStoreByChainAndRegion :one
SELECT store_id, retailer, region_id, external_store_id, name, latitude, longitude, is_deleted, date_created_utc, last_updated_utc FROM store
WHERE retailer = $1::store_chain
  AND region_id = $2::text
  AND is_deleted = false
`

type FindStoreByChainAndRegionParams struct {
	Retailer StoreChain
	RegionID string
}

func (q *Queries) FindStoreByChainAndRegion(ctx context.Context, arg FindStoreByChainAndRegionParams) (Store, error) {
	row := q.db.QueryRow(ctx, findStoreByChainAndRegion, arg.Retailer, arg.RegionID)
	var i Store
	err := row.Scan(
		&i.StoreID,
		&i.Retailer,
		&i.RegionID,
		&i.ExternalStoreID,
		&i.Name,
		&i.Latitude,
		&i.Longitude,
		&i.IsDeleted,
		&i.DateCreatedUtc,
		&i.LastUpdatedUtc,
	)
	return i, err
}

const listStoresByChain = `-- name: ListStoresByChain :many
SELECT store_id, retailer, region_id, external_store_id, name, latitude, longitude, is_deleted, date_created_utc, last_updated_utc FROM store
WHERE retailer = $1::store_chain AND is_deleted = false
ORDER BY region_id
`

func (q *Queries) ListStoresByChain(ctx context.Context, retailer StoreChain) ([]Store, error) {
	rows, err := q.db.Query(ctx, listStoresByChain, retailer)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Store
	for rows.Next() {
		var i Store
		if err := rows.Scan(
			&i.StoreID,
			&i.Retailer,
			&i.RegionID,
			&i.ExternalStoreID,
			&i.Name,
			&i.Latitude,
			&i.Longitude,
			&i.IsDeleted,
			&i.DateCreatedUtc,
			&i.LastUpdatedUtc,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertStore = `-- name: UpsertStore :one
INSERT INTO store (retailer, region_id, external_store_id, name, latitude, longitude)
VALUES ($1::store_chain, $2::text, $3::text, $4::text, $5::double precision, $6::double precision)
ON CONFLICT (external_store_id) WHERE external_store_id IS NOT NULL DO UPDATE
SET name            = EXCLUDED.name,
    retailer        = EXCLUDED.retailer,
    latitude        = EXCLUDED.latitude,
    longitude       = EXCLUDED.longitude,
    last_updated_utc = now(),
    is_deleted       = false
RETURNING store_id, retailer, region_id, external_store_id, name, latitude, longitude, is_deleted, date_created_utc, last_updated_utc
`

type UpsertStoreParams struct {
	Retailer        StoreChain
	RegionID        string
	ExternalStoreID string
	Name            string
	Latitude        float64
	Longitude       float64
}

func (q *Queries) UpsertStore(ctx context.Context, arg UpsertStoreParams) (Store, error) {
	row := q.db.QueryRow(ctx, upsertStore,
		arg.Retailer,
		arg.RegionID,
		arg.ExternalStoreID,
		arg.Name,
		arg.Latitude,
		arg.Longitude,
	)
	var i Store
	err := row.Scan(
		&i.StoreID,
		&i.Retailer,
		&i.RegionID,
		&i.ExternalStoreID,
		&i.Name,
		&i.Latitude,
		&i.Longitude,
		&i.IsDeleted,
		&i.DateCreatedUtc,
		&i.LastUpdatedUtc,
	)
	return i, err
}
