// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sync_run.sql

package entities

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const completeSyncRun = `-- name: CompleteSyncRun :one
UPDATE sync_run
SET status           = 'SUCCEEDED',
    finished_at_utc  = now(),
    products_created = $2,
    products_matched = $3,
    store_products   = $4,
    delisted         = $5,
    last_updated_utc = now()
WHERE sync_run_id = $1
RETURNING sync_run_id, status, started_at_utc, finished_at_utc, heartbeat_at_utc, products_created, products_matched, store_products, delisted, error_message, is_deleted, date_created_utc, last_updated_utc
`

type CompleteSyncRunParams struct {
	SyncRunID       pgtype.UUID
	ProductsCreated int32
	ProductsMatched int32
	StoreProducts   int32
	Delisted        int64
}

func (q *Queries) CompleteSyncRun(ctx context.Context, arg CompleteSyncRunParams) (SyncRun, error) {
	row := q.db.QueryRow(ctx, completeSyncRun,
		arg.SyncRunID,
		arg.ProductsCreated,
		arg.ProductsMatched,
		arg.StoreProducts,
		arg.Delisted,
	)
	var i SyncRun
	err := row.Scan(
		&i.SyncRunID,
		&i.Status,
		&i.StartedAtUtc,
		&i.FinishedAtUtc,
		&i.HeartbeatAtUtc,
		&i.ProductsCreated,
		&i.ProductsMatched,
		&i.StoreProducts,
		&i.Delisted,
		&i.ErrorMessage,
		&i.IsDeleted,
		&i.DateCreatedUtc,
		&i.LastUpdatedUtc,
	)
	return i, err
}

const failSyncRun = `-- name: FailSyncRun :one
UPDATE sync_run
SET status           = 'FAILED',
    finished_at_utc  = now(),
    error_message    = $2,
    last_updated_utc = now()
WHERE sync_run_id = $1
RETURNING sync_run_id, status, started_at_utc, finished_at_utc, heartbeat_at_utc, products_created, products_matched, store_products, delisted, error_message, is_deleted, date_created_utc, last_updated_utc
`

type FailSyncRunParams struct {
	SyncRunID    pgtype.UUID
	ErrorMessage pgtype.Text
}

func (q *Queries) FailSyncRun(ctx context.Context, arg FailSyncRunParams) (SyncRun, error) {
	row := q.db.QueryRow(ctx, failSyncRun, arg.SyncRunID, arg.ErrorMessage)
	var i SyncRun
	err := row.Scan(
		&i.SyncRunID,
		&i.Status,
		&i.StartedAtUtc,
		&i.FinishedAtUtc,
		&i.HeartbeatAtUtc,
		&i.ProductsCreated,
		&i.ProductsMatched,
		&i.StoreProducts,
		&i.Delisted,
		&i.ErrorMessage,
		&i.IsDeleted,
		&i.DateCreatedUtc,
		&i.LastUpdatedUtc,
	)
	return i, err
}

const findRunningSyncRun = `-- name: FindRunningSyncRun :one
SELECT sync_run_id, status, started_at_utc, finished_at_utc, heartbeat_at_utc, products_created, products_matched, store_products, delisted, error_message, is_deleted, date_created_utc, last_updated_utc FROM sync_run WHERE status = 'RUNNING'
`

func (q *Queries) FindRunningSyncRun(ctx context.Context) (SyncRun, error) {
	row := q.db.QueryRow(ctx, findRunningSyncRun)
	var i SyncRun
	err := row.Scan(
		&i.SyncRunID,
		&i.Status,
		&i.StartedAtUtc,
		&i.FinishedAtUtc,
		&i.HeartbeatAtUtc,
		&i.ProductsCreated,
		&i.ProductsMatched,
		&i.StoreProducts,
		&i.Delisted,
		&i.ErrorMessage,
		&i.IsDeleted,
		&i.DateCreatedUtc,
		&i.LastUpdatedUtc,
	)
	return i, err
}

const heartbeatSyncRun = `-- name: HeartbeatSyncRun :exec
UPDATE sync_run
SET heartbeat_at_utc = now(), last_updated_utc = now()
WHERE sync_run_id = $1 AND status = 'RUNNING'
`

func (q *Queries) HeartbeatSyncRun(ctx context.Context, syncRunID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, heartbeatSyncRun, syncRunID)
	return err
}

const latestSyncRun = `-- name: LatestSyncRun :one
SELECT sync_run_id, status, started_at_utc, finished_at_utc, heartbeat_at_utc, products_created, products_matched, store_products, delisted, error_message, is_deleted, date_created_utc, last_updated_utc FROM sync_run ORDER BY started_at_utc DESC LIMIT 1
`

func (q *Queries) LatestSyncRun(ctx context.Context) (SyncRun, error) {
	row := q.db.QueryRow(ctx, latestSyncRun)
	var i SyncRun
	err := row.Scan(
		&i.SyncRunID,
		&i.Status,
		&i.StartedAtUtc,
		&i.FinishedAtUtc,
		&i.HeartbeatAtUtc,
		&i.ProductsCreated,
		&i.ProductsMatched,
		&i.StoreProducts,
		&i.Delisted,
		&i.ErrorMessage,
		&i.IsDeleted,
		&i.DateCreatedUtc,
		&i.LastUpdatedUtc,
	)
	return i, err
}

const reclaimStaleSyncRuns = `-- name: ReclaimStaleSyncRuns :execrows
UPDATE sync_run
SET status           = 'FAILED',
    finished_at_utc  = now(),
    error_message    = 'run abandoned: heartbeat stopped',
    last_updated_utc = now()
WHERE status = 'RUNNING' AND heartbeat_at_utc < $1
`

// Marks runs whose heartbeat has gone quiet as FAILED, so a process that died mid-run
// cannot block every future sync.
func (q *Queries) ReclaimStaleSyncRuns(ctx context.Context, heartbeatAtUtc pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, reclaimStaleSyncRuns, heartbeatAtUtc)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const startSyncRun = `-- name: StartSyncRun :one
INSERT INTO sync_run (status) VALUES ('RUNNING')
RETURNING sync_run_id, status, started_at_utc, finished_at_utc, heartbeat_at_utc, products_created, products_matched, store_products, delisted, error_message, is_deleted, date_created_utc, last_updated_utc
`

// Fails with a unique violation if a run is already RUNNING, which is how the caller
// learns a sync is in progress. Reclaim stale runs first.
func (q *Queries) StartSyncRun(ctx context.Context) (SyncRun, error) {
	row := q.db.QueryRow(ctx, startSyncRun)
	var i SyncRun
	err := row.Scan(
		&i.SyncRunID,
		&i.Status,
		&i.StartedAtUtc,
		&i.FinishedAtUtc,
		&i.HeartbeatAtUtc,
		&i.ProductsCreated,
		&i.ProductsMatched,
		&i.StoreProducts,
		&i.Delisted,
		&i.ErrorMessage,
		&i.IsDeleted,
		&i.DateCreatedUtc,
		&i.LastUpdatedUtc,
	)
	return i, err
}
